version: '3.7'

services:
  db:
    image: postgres:alpine
    container_name: db
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

  backend:
    build: ./backend
    restart: always
    container_name: backend-achievement
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    container_name: frontend-service-achievement
    restart: unless-stopped
    build:
      context: ./frontend

volumes:
  pgdata:
  node_modules_backend:
  node_modules_frontend:
