version: '3.7'

services:
  backend:
    volumes:
      - ./backend:/backend
      - node_modules_backend:/backend/node_modules
    ports:
      - 5000:5000

  db:
    ports:
      - 5432:5432

  frontend:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/frontend
      - node_modules_frontend:/frontend/node_modules
    ports:
      - '3000:3000'
